back_main_menu = "Asosiy menu🏠"
back_main_menu_ru = "Главное меню🏠"
adverts = "Reklama 📨"
forward_advert = "Forward 📥"
none_advert = "Oddiy 📥"
cabinet = "Kabinet 👤"
cabinet_ru = "Кабинет 👤"
uz_language = "🇺🇿 O'zbek"
ru_language = "🇷🇺 Русский"
choice_language = "Tilni o'zgartirish 🌐"
choice_language_ru = "Изменить язык 🌐"
contact = 'Aloqa ☎️'
contact_ru = 'Контакты ☎️'
social_networks = 'Ijtimoiy tarmoqlar 🌐'
social_networks_ru = 'Социальные сети 🌐'
location = 'Joylashuv 📍'
location_ru = 'Местоположение 📍'
search_analyses = 'Analiz qidirish 🔍'
search_analyses_ru = 'Поиск анализа 🔍'
get_analyses_result = 'Analiz javobini olish 📨'
get_analyses_result_ru = 'Получите ответ на анализ 📨'
ask_question = 'Talab va Istaklar 💡'
ask_question_ru = 'Спрос и желание 💡'
