# Generated by Django 5.0.1 on 2024-09-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='ru_info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='types',
            name='ru_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
