# Generated by Django 5.0.1 on 2024-09-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_type', '0002_types_ru_info_types_ru_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='category',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='types',
            name='ru_category',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
