# Generated by Django 5.0.1 on 2024-09-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_type', '0003_types_category_types_ru_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types',
            name='category',
            field=models.CharField(choices=[('gormon', 'Gormonal tekshiruvlar'), ('bioximik', 'Bioximik tekshiruvlar'), ('bakteriologik', 'Bakteriologik tekshiruvlar'), ('psr', 'PSR tekshiruvlar'), ('klinik', 'Klinik laborator tekshiruvlar'), ('mikroskopik', 'Mikroskopik tekshiruvlar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='types',
            name='ru_category',
            field=models.CharField(choices=[('gormon', 'Гормональные исследования'), ('bioximik', 'Биохимические исследования'), ('bakteriologik', 'Бактериологические исследования'), ('psr', 'ПЦР исследования'), ('klinik', 'Клинические лабораторные исследования'), ('mikroskopik', 'Микроскопические исследования')], max_length=100),
        ),
    ]
